version: '2'

services:

  simple-server-node:
    build: ./simple-server-node
    ports:
      - 8080:80
    restart: always

  wifi-connect:
    build: ./wifi-connect
    network_mode: host
    privileged: true
    restart: always
    labels:
      io.balena.features.dbus: '1'

  bluetooth-audio:
    build: ./balena-sound/bluetooth-audio
    network_mode: host
    restart: always
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth

volumes:
  bluetoothcache: